#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaOnline
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDCARROONLINE")]
	public partial class CarritoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCategoria(Categoria instance);
    partial void UpdateCategoria(Categoria instance);
    partial void DeleteCategoria(Categoria instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertEstado(Estado instance);
    partial void UpdateEstado(Estado instance);
    partial void DeleteEstado(Estado instance);
    partial void InsertFactura(Factura instance);
    partial void UpdateFactura(Factura instance);
    partial void DeleteFactura(Factura instance);
    partial void InsertPromocione(Promocione instance);
    partial void UpdatePromocione(Promocione instance);
    partial void DeletePromocione(Promocione instance);
    partial void InsertRegistro(Registro instance);
    partial void UpdateRegistro(Registro instance);
    partial void DeleteRegistro(Registro instance);
    partial void InsertProducto(Producto instance);
    partial void UpdateProducto(Producto instance);
    partial void DeleteProducto(Producto instance);
    #endregion
		
		public CarritoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TIENDAONLINEConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CarritoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarritoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarritoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarritoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Categoria> Categorias
		{
			get
			{
				return this.GetTable<Categoria>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Estado> Estados
		{
			get
			{
				return this.GetTable<Estado>();
			}
		}
		
		public System.Data.Linq.Table<Factura> Facturas
		{
			get
			{
				return this.GetTable<Factura>();
			}
		}
		
		public System.Data.Linq.Table<Promocione> Promociones
		{
			get
			{
				return this.GetTable<Promocione>();
			}
		}
		
		public System.Data.Linq.Table<Registro> Registros
		{
			get
			{
				return this.GetTable<Registro>();
			}
		}
		
		public System.Data.Linq.Table<Producto> Productos
		{
			get
			{
				return this.GetTable<Producto>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categorias")]
	public partial class Categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_categoria;
		
		private string _Nombre_categoria;
		
		private EntitySet<Producto> _Productos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_categoriaChanging(int value);
    partial void OnId_categoriaChanged();
    partial void OnNombre_categoriaChanging(string value);
    partial void OnNombre_categoriaChanged();
    #endregion
		
		public Categoria()
		{
			this._Productos = new EntitySet<Producto>(new Action<Producto>(this.attach_Productos), new Action<Producto>(this.detach_Productos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_categoria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_categoria
		{
			get
			{
				return this._Id_categoria;
			}
			set
			{
				if ((this._Id_categoria != value))
				{
					this.OnId_categoriaChanging(value);
					this.SendPropertyChanging();
					this._Id_categoria = value;
					this.SendPropertyChanged("Id_categoria");
					this.OnId_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_categoria", DbType="VarChar(100)")]
		public string Nombre_categoria
		{
			get
			{
				return this._Nombre_categoria;
			}
			set
			{
				if ((this._Nombre_categoria != value))
				{
					this.OnNombre_categoriaChanging(value);
					this.SendPropertyChanging();
					this._Nombre_categoria = value;
					this.SendPropertyChanged("Nombre_categoria");
					this.OnNombre_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_Producto", Storage="_Productos", ThisKey="Id_categoria", OtherKey="Id_categoria")]
		public EntitySet<Producto> Productos
		{
			get
			{
				return this._Productos;
			}
			set
			{
				this._Productos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Productos(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = this;
		}
		
		private void detach_Productos(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_usuario;
		
		private string _codigo;
		
		private string _clave;
		
		private System.Nullable<int> _Id_registro;
		
		private EntitySet<Factura> _Facturas;
		
		private EntityRef<Registro> _Registro;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_usuarioChanging(int value);
    partial void OnId_usuarioChanged();
    partial void OncodigoChanging(string value);
    partial void OncodigoChanged();
    partial void OnclaveChanging(string value);
    partial void OnclaveChanged();
    partial void OnId_registroChanging(System.Nullable<int> value);
    partial void OnId_registroChanged();
    #endregion
		
		public Usuario()
		{
			this._Facturas = new EntitySet<Factura>(new Action<Factura>(this.attach_Facturas), new Action<Factura>(this.detach_Facturas));
			this._Registro = default(EntityRef<Registro>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_usuario
		{
			get
			{
				return this._Id_usuario;
			}
			set
			{
				if ((this._Id_usuario != value))
				{
					this.OnId_usuarioChanging(value);
					this.SendPropertyChanging();
					this._Id_usuario = value;
					this.SendPropertyChanged("Id_usuario");
					this.OnId_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="VarChar(50)")]
		public string codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clave", DbType="VarChar(50)")]
		public string clave
		{
			get
			{
				return this._clave;
			}
			set
			{
				if ((this._clave != value))
				{
					this.OnclaveChanging(value);
					this.SendPropertyChanging();
					this._clave = value;
					this.SendPropertyChanged("clave");
					this.OnclaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_registro", DbType="Int")]
		public System.Nullable<int> Id_registro
		{
			get
			{
				return this._Id_registro;
			}
			set
			{
				if ((this._Id_registro != value))
				{
					if (this._Registro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_registroChanging(value);
					this.SendPropertyChanging();
					this._Id_registro = value;
					this.SendPropertyChanged("Id_registro");
					this.OnId_registroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Factura", Storage="_Facturas", ThisKey="Id_usuario", OtherKey="Id_usuario")]
		public EntitySet<Factura> Facturas
		{
			get
			{
				return this._Facturas;
			}
			set
			{
				this._Facturas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Registro_Usuario", Storage="_Registro", ThisKey="Id_registro", OtherKey="Id_registro", IsForeignKey=true)]
		public Registro Registro
		{
			get
			{
				return this._Registro.Entity;
			}
			set
			{
				Registro previousValue = this._Registro.Entity;
				if (((previousValue != value) 
							|| (this._Registro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Registro.Entity = null;
						previousValue.Usuarios.Remove(this);
					}
					this._Registro.Entity = value;
					if ((value != null))
					{
						value.Usuarios.Add(this);
						this._Id_registro = value.Id_registro;
					}
					else
					{
						this._Id_registro = default(Nullable<int>);
					}
					this.SendPropertyChanged("Registro");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Facturas(Factura entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Facturas(Factura entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Estados")]
	public partial class Estado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_estado;
		
		private string _Nombre_estado;
		
		private EntitySet<Factura> _Facturas;
		
		private EntitySet<Producto> _Productos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_estadoChanging(int value);
    partial void OnId_estadoChanged();
    partial void OnNombre_estadoChanging(string value);
    partial void OnNombre_estadoChanged();
    #endregion
		
		public Estado()
		{
			this._Facturas = new EntitySet<Factura>(new Action<Factura>(this.attach_Facturas), new Action<Factura>(this.detach_Facturas));
			this._Productos = new EntitySet<Producto>(new Action<Producto>(this.attach_Productos), new Action<Producto>(this.detach_Productos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_estado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_estado
		{
			get
			{
				return this._Id_estado;
			}
			set
			{
				if ((this._Id_estado != value))
				{
					this.OnId_estadoChanging(value);
					this.SendPropertyChanging();
					this._Id_estado = value;
					this.SendPropertyChanged("Id_estado");
					this.OnId_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_estado", DbType="VarChar(100)")]
		public string Nombre_estado
		{
			get
			{
				return this._Nombre_estado;
			}
			set
			{
				if ((this._Nombre_estado != value))
				{
					this.OnNombre_estadoChanging(value);
					this.SendPropertyChanging();
					this._Nombre_estado = value;
					this.SendPropertyChanged("Nombre_estado");
					this.OnNombre_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_Factura", Storage="_Facturas", ThisKey="Id_estado", OtherKey="Id_estado")]
		public EntitySet<Factura> Facturas
		{
			get
			{
				return this._Facturas;
			}
			set
			{
				this._Facturas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_Producto", Storage="_Productos", ThisKey="Id_estado", OtherKey="Id_estado")]
		public EntitySet<Producto> Productos
		{
			get
			{
				return this._Productos;
			}
			set
			{
				this._Productos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Facturas(Factura entity)
		{
			this.SendPropertyChanging();
			entity.Estado = this;
		}
		
		private void detach_Facturas(Factura entity)
		{
			this.SendPropertyChanging();
			entity.Estado = null;
		}
		
		private void attach_Productos(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Estado = this;
		}
		
		private void detach_Productos(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Estado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Facturas")]
	public partial class Factura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_factura;
		
		private System.Nullable<int> _Id_producto;
		
		private System.Nullable<decimal> _Precio;
		
		private System.Nullable<int> _Cantidad;
		
		private System.Nullable<decimal> _Total;
		
		private System.Nullable<int> _Id_estado;
		
		private System.Nullable<int> _Id_usuario;
		
		private EntityRef<Estado> _Estado;
		
		private EntityRef<Usuario> _Usuario;
		
		private EntityRef<Producto> _Producto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_facturaChanging(int value);
    partial void OnId_facturaChanged();
    partial void OnId_productoChanging(System.Nullable<int> value);
    partial void OnId_productoChanged();
    partial void OnPrecioChanging(System.Nullable<decimal> value);
    partial void OnPrecioChanged();
    partial void OnCantidadChanging(System.Nullable<int> value);
    partial void OnCantidadChanged();
    partial void OnTotalChanging(System.Nullable<decimal> value);
    partial void OnTotalChanged();
    partial void OnId_estadoChanging(System.Nullable<int> value);
    partial void OnId_estadoChanged();
    partial void OnId_usuarioChanging(System.Nullable<int> value);
    partial void OnId_usuarioChanged();
    #endregion
		
		public Factura()
		{
			this._Estado = default(EntityRef<Estado>);
			this._Usuario = default(EntityRef<Usuario>);
			this._Producto = default(EntityRef<Producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_factura", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_factura
		{
			get
			{
				return this._Id_factura;
			}
			set
			{
				if ((this._Id_factura != value))
				{
					this.OnId_facturaChanging(value);
					this.SendPropertyChanging();
					this._Id_factura = value;
					this.SendPropertyChanged("Id_factura");
					this.OnId_facturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_producto", DbType="Int")]
		public System.Nullable<int> Id_producto
		{
			get
			{
				return this._Id_producto;
			}
			set
			{
				if ((this._Id_producto != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_productoChanging(value);
					this.SendPropertyChanging();
					this._Id_producto = value;
					this.SendPropertyChanged("Id_producto");
					this.OnId_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this.OnPrecioChanging(value);
					this.SendPropertyChanging();
					this._Precio = value;
					this.SendPropertyChanged("Precio");
					this.OnPrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this.OnCantidadChanging(value);
					this.SendPropertyChanging();
					this._Cantidad = value;
					this.SendPropertyChanged("Cantidad");
					this.OnCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this.OnTotalChanging(value);
					this.SendPropertyChanging();
					this._Total = value;
					this.SendPropertyChanged("Total");
					this.OnTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_estado", DbType="Int")]
		public System.Nullable<int> Id_estado
		{
			get
			{
				return this._Id_estado;
			}
			set
			{
				if ((this._Id_estado != value))
				{
					if (this._Estado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_estadoChanging(value);
					this.SendPropertyChanging();
					this._Id_estado = value;
					this.SendPropertyChanged("Id_estado");
					this.OnId_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_usuario", DbType="Int")]
		public System.Nullable<int> Id_usuario
		{
			get
			{
				return this._Id_usuario;
			}
			set
			{
				if ((this._Id_usuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_usuarioChanging(value);
					this.SendPropertyChanging();
					this._Id_usuario = value;
					this.SendPropertyChanged("Id_usuario");
					this.OnId_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_Factura", Storage="_Estado", ThisKey="Id_estado", OtherKey="Id_estado", IsForeignKey=true)]
		public Estado Estado
		{
			get
			{
				return this._Estado.Entity;
			}
			set
			{
				Estado previousValue = this._Estado.Entity;
				if (((previousValue != value) 
							|| (this._Estado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Estado.Entity = null;
						previousValue.Facturas.Remove(this);
					}
					this._Estado.Entity = value;
					if ((value != null))
					{
						value.Facturas.Add(this);
						this._Id_estado = value.Id_estado;
					}
					else
					{
						this._Id_estado = default(Nullable<int>);
					}
					this.SendPropertyChanged("Estado");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Factura", Storage="_Usuario", ThisKey="Id_usuario", OtherKey="Id_usuario", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Facturas.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Facturas.Add(this);
						this._Id_usuario = value.Id_usuario;
					}
					else
					{
						this._Id_usuario = default(Nullable<int>);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Factura", Storage="_Producto", ThisKey="Id_producto", OtherKey="Id_producto", IsForeignKey=true)]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.Facturas.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.Facturas.Add(this);
						this._Id_producto = value.Id_producto;
					}
					else
					{
						this._Id_producto = default(Nullable<int>);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Promociones")]
	public partial class Promocione : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_promocion;
		
		private System.Nullable<decimal> _Descuento;
		
		private System.Nullable<System.DateTime> _Fecha_inicio;
		
		private System.Nullable<System.DateTime> _Fecha_fin;
		
		private string _Descripcion;
		
		private EntitySet<Producto> _Productos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_promocionChanging(int value);
    partial void OnId_promocionChanged();
    partial void OnDescuentoChanging(System.Nullable<decimal> value);
    partial void OnDescuentoChanged();
    partial void OnFecha_inicioChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_inicioChanged();
    partial void OnFecha_finChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_finChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    #endregion
		
		public Promocione()
		{
			this._Productos = new EntitySet<Producto>(new Action<Producto>(this.attach_Productos), new Action<Producto>(this.detach_Productos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_promocion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_promocion
		{
			get
			{
				return this._Id_promocion;
			}
			set
			{
				if ((this._Id_promocion != value))
				{
					this.OnId_promocionChanging(value);
					this.SendPropertyChanging();
					this._Id_promocion = value;
					this.SendPropertyChanged("Id_promocion");
					this.OnId_promocionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descuento", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Descuento
		{
			get
			{
				return this._Descuento;
			}
			set
			{
				if ((this._Descuento != value))
				{
					this.OnDescuentoChanging(value);
					this.SendPropertyChanging();
					this._Descuento = value;
					this.SendPropertyChanged("Descuento");
					this.OnDescuentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_inicio", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_inicio
		{
			get
			{
				return this._Fecha_inicio;
			}
			set
			{
				if ((this._Fecha_inicio != value))
				{
					this.OnFecha_inicioChanging(value);
					this.SendPropertyChanging();
					this._Fecha_inicio = value;
					this.SendPropertyChanged("Fecha_inicio");
					this.OnFecha_inicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_fin", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_fin
		{
			get
			{
				return this._Fecha_fin;
			}
			set
			{
				if ((this._Fecha_fin != value))
				{
					this.OnFecha_finChanging(value);
					this.SendPropertyChanging();
					this._Fecha_fin = value;
					this.SendPropertyChanged("Fecha_fin");
					this.OnFecha_finChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(1500)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Promocione_Producto", Storage="_Productos", ThisKey="Id_promocion", OtherKey="Id_promo")]
		public EntitySet<Producto> Productos
		{
			get
			{
				return this._Productos;
			}
			set
			{
				this._Productos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Productos(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Promocione = this;
		}
		
		private void detach_Productos(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Promocione = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Registros")]
	public partial class Registro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_registro;
		
		private string _Nombres;
		
		private string _Apellidos;
		
		private string _Correo;
		
		private System.Nullable<char> _sexo;
		
		private EntitySet<Usuario> _Usuarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_registroChanging(int value);
    partial void OnId_registroChanged();
    partial void OnNombresChanging(string value);
    partial void OnNombresChanged();
    partial void OnApellidosChanging(string value);
    partial void OnApellidosChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnsexoChanging(System.Nullable<char> value);
    partial void OnsexoChanged();
    #endregion
		
		public Registro()
		{
			this._Usuarios = new EntitySet<Usuario>(new Action<Usuario>(this.attach_Usuarios), new Action<Usuario>(this.detach_Usuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_registro", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_registro
		{
			get
			{
				return this._Id_registro;
			}
			set
			{
				if ((this._Id_registro != value))
				{
					this.OnId_registroChanging(value);
					this.SendPropertyChanging();
					this._Id_registro = value;
					this.SendPropertyChanged("Id_registro");
					this.OnId_registroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(200)")]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this.OnNombresChanging(value);
					this.SendPropertyChanging();
					this._Nombres = value;
					this.SendPropertyChanged("Nombres");
					this.OnNombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(200)")]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this.OnApellidosChanging(value);
					this.SendPropertyChanging();
					this._Apellidos = value;
					this.SendPropertyChanged("Apellidos");
					this.OnApellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(200)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="Char(1)")]
		public System.Nullable<char> sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				if ((this._sexo != value))
				{
					this.OnsexoChanging(value);
					this.SendPropertyChanging();
					this._sexo = value;
					this.SendPropertyChanged("sexo");
					this.OnsexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Registro_Usuario", Storage="_Usuarios", ThisKey="Id_registro", OtherKey="Id_registro")]
		public EntitySet<Usuario> Usuarios
		{
			get
			{
				return this._Usuarios;
			}
			set
			{
				this._Usuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuarios(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Registro = this;
		}
		
		private void detach_Usuarios(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Registro = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Productos")]
	public partial class Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_producto;
		
		private System.Nullable<int> _cantidad;
		
		private string _Nombre_producto;
		
		private System.Nullable<int> _Id_categoria;
		
		private System.Nullable<decimal> _Precio;
		
		private System.Nullable<int> _Id_promo;
		
		private string _Imagen;
		
		private System.Nullable<int> _Id_estado;
		
		private EntitySet<Factura> _Facturas;
		
		private EntityRef<Categoria> _Categoria;
		
		private EntityRef<Estado> _Estado;
		
		private EntityRef<Promocione> _Promocione;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_productoChanging(int value);
    partial void OnId_productoChanged();
    partial void OncantidadChanging(System.Nullable<int> value);
    partial void OncantidadChanged();
    partial void OnNombre_productoChanging(string value);
    partial void OnNombre_productoChanged();
    partial void OnId_categoriaChanging(System.Nullable<int> value);
    partial void OnId_categoriaChanged();
    partial void OnPrecioChanging(System.Nullable<decimal> value);
    partial void OnPrecioChanged();
    partial void OnId_promoChanging(System.Nullable<int> value);
    partial void OnId_promoChanged();
    partial void OnImagenChanging(string value);
    partial void OnImagenChanged();
    partial void OnId_estadoChanging(System.Nullable<int> value);
    partial void OnId_estadoChanged();
    #endregion
		
		public Producto()
		{
			this._Facturas = new EntitySet<Factura>(new Action<Factura>(this.attach_Facturas), new Action<Factura>(this.detach_Facturas));
			this._Categoria = default(EntityRef<Categoria>);
			this._Estado = default(EntityRef<Estado>);
			this._Promocione = default(EntityRef<Promocione>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_producto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_producto
		{
			get
			{
				return this._Id_producto;
			}
			set
			{
				if ((this._Id_producto != value))
				{
					this.OnId_productoChanging(value);
					this.SendPropertyChanging();
					this._Id_producto = value;
					this.SendPropertyChanged("Id_producto");
					this.OnId_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int")]
		public System.Nullable<int> cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_producto", DbType="VarChar(100)")]
		public string Nombre_producto
		{
			get
			{
				return this._Nombre_producto;
			}
			set
			{
				if ((this._Nombre_producto != value))
				{
					this.OnNombre_productoChanging(value);
					this.SendPropertyChanging();
					this._Nombre_producto = value;
					this.SendPropertyChanged("Nombre_producto");
					this.OnNombre_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_categoria", DbType="Int")]
		public System.Nullable<int> Id_categoria
		{
			get
			{
				return this._Id_categoria;
			}
			set
			{
				if ((this._Id_categoria != value))
				{
					if (this._Categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_categoriaChanging(value);
					this.SendPropertyChanging();
					this._Id_categoria = value;
					this.SendPropertyChanged("Id_categoria");
					this.OnId_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this.OnPrecioChanging(value);
					this.SendPropertyChanging();
					this._Precio = value;
					this.SendPropertyChanged("Precio");
					this.OnPrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_promo", DbType="Int")]
		public System.Nullable<int> Id_promo
		{
			get
			{
				return this._Id_promo;
			}
			set
			{
				if ((this._Id_promo != value))
				{
					if (this._Promocione.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_promoChanging(value);
					this.SendPropertyChanging();
					this._Id_promo = value;
					this.SendPropertyChanged("Id_promo");
					this.OnId_promoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imagen", DbType="VarChar(200)")]
		public string Imagen
		{
			get
			{
				return this._Imagen;
			}
			set
			{
				if ((this._Imagen != value))
				{
					this.OnImagenChanging(value);
					this.SendPropertyChanging();
					this._Imagen = value;
					this.SendPropertyChanged("Imagen");
					this.OnImagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_estado", DbType="Int")]
		public System.Nullable<int> Id_estado
		{
			get
			{
				return this._Id_estado;
			}
			set
			{
				if ((this._Id_estado != value))
				{
					if (this._Estado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_estadoChanging(value);
					this.SendPropertyChanging();
					this._Id_estado = value;
					this.SendPropertyChanged("Id_estado");
					this.OnId_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Factura", Storage="_Facturas", ThisKey="Id_producto", OtherKey="Id_producto")]
		public EntitySet<Factura> Facturas
		{
			get
			{
				return this._Facturas;
			}
			set
			{
				this._Facturas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_Producto", Storage="_Categoria", ThisKey="Id_categoria", OtherKey="Id_categoria", IsForeignKey=true)]
		public Categoria Categoria
		{
			get
			{
				return this._Categoria.Entity;
			}
			set
			{
				Categoria previousValue = this._Categoria.Entity;
				if (((previousValue != value) 
							|| (this._Categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categoria.Entity = null;
						previousValue.Productos.Remove(this);
					}
					this._Categoria.Entity = value;
					if ((value != null))
					{
						value.Productos.Add(this);
						this._Id_categoria = value.Id_categoria;
					}
					else
					{
						this._Id_categoria = default(Nullable<int>);
					}
					this.SendPropertyChanged("Categoria");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_Producto", Storage="_Estado", ThisKey="Id_estado", OtherKey="Id_estado", IsForeignKey=true)]
		public Estado Estado
		{
			get
			{
				return this._Estado.Entity;
			}
			set
			{
				Estado previousValue = this._Estado.Entity;
				if (((previousValue != value) 
							|| (this._Estado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Estado.Entity = null;
						previousValue.Productos.Remove(this);
					}
					this._Estado.Entity = value;
					if ((value != null))
					{
						value.Productos.Add(this);
						this._Id_estado = value.Id_estado;
					}
					else
					{
						this._Id_estado = default(Nullable<int>);
					}
					this.SendPropertyChanged("Estado");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Promocione_Producto", Storage="_Promocione", ThisKey="Id_promo", OtherKey="Id_promocion", IsForeignKey=true)]
		public Promocione Promocione
		{
			get
			{
				return this._Promocione.Entity;
			}
			set
			{
				Promocione previousValue = this._Promocione.Entity;
				if (((previousValue != value) 
							|| (this._Promocione.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Promocione.Entity = null;
						previousValue.Productos.Remove(this);
					}
					this._Promocione.Entity = value;
					if ((value != null))
					{
						value.Productos.Add(this);
						this._Id_promo = value.Id_promocion;
					}
					else
					{
						this._Id_promo = default(Nullable<int>);
					}
					this.SendPropertyChanged("Promocione");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Facturas(Factura entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_Facturas(Factura entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
	}
}
#pragma warning restore 1591
